services:
   fastapi:
     build: .
     environment: 
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379 
     networks:
      - python-net
     depends_on:
        - postgres
        - redis
  
   redis:
     image: redis:bookworm
     networks:
      - python-net

   postgres:
    image: postgres:16.8-alpine3.20
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - python-net

   nginx:
     image: nginx:stable-bookworm-perl
     ports:
       - "80:80"
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
        - fastapi
     networks:
      - python-net


volumes: 
  postgres_data:

networks:
  python-net:

